# Cleaning methodology for pollutant data

This notebook contains the key steps taken to gather and clean air pollution data. As the data set is quite large and can only be downloaded in small chunks, we are currently investigation different ways of downloading the data in order to increase efficiency. As we continue to explore the data, more substantial filtering and cleaning will take place.

In [1]:
import pandas as pd
import numpy as np

## Step 1: Identify boundary for monitoring. 

Having manually sifted through the data, we were able to split several monitoring sites into "inner" and "outer" ranges based on their geographic location. The data points closest to our area of focus (Heathrow Airport) have been categorised as "inner" locations and will be vital in our investigation into emissions. The "outer" locations will be used as a way of comparisson to gain a deeper understanding of the scale of the impact arising from air pollution.

|CCG | Borough| Inner location - monitoring station| Outer location - monitoring site|
|---:|:-----|:-----------|:------------|
|Hillingdon |Hillingdon| Hillingdon South Ruislip, Hillingdon 2 Hillingdon Hospital, Hillingdon Oxford Avenue, Hillingdon Harmondsworth, Hillingdon Harmondsworth Osiris, Hillingdon Hayes, Heathrow LHR2, Heathrow Bath Road, Hillingdon Sipson, Heathrow Green Gates| |
|East Berkshire | Slough |Slough Town Centre Wellington Street,Slough Brands Hill London Road,Slough Windmill Bath Road,Slough Colnbrook,Slough Town Centre A4,Slough Lakeside 1 Osiris,Slough Colnbrook Osiris,Slough Chalvey,Slough Lakeside 2,Slough Lakeside 2 Osiris,Slough - Dennis Way LP11,Slough - Monksfield Way LP20,Slough - The Hawthorns LP2,Slough - Erica Close LP3,Slough - Hatton Avenue LP13,Slough - St Andrews Way LP12,Slough - The Hawthorns LP10,Slough - Francis Way LP13,Slough - The Hawthorns LP1,Slough - Monksfield Way LP19,Slough - Brighton Spur LP3,Slough - Bower Way LP1,Slough - Hatton Avenue LP3,Slough - Cinder Track LP37|
|Hounslow| Hounslow | Hounslow Cranford, Hounslow Chiswick, Hounslow Brentford, Hounslow Heston, Hounslow Hatton Cross, Hounslow Feltham, Hounslow Gunnersbury |
|Ealing | Ealing | Ealing Horn Lane
|Buckinghamshire|South Bucks|Iver Thorney Lane North, Iver North Park Road, Iver Primary School|
|Surrey Heartlands|Richmond|- |Elmbridge|
| - | Spelthorne | Spelthorne Shepperton Squire's Bridge Road, Spelthorne knowle Green, Spelthorne Sunbury Cross, Heathrow Oaks Road|
| - |Waverly and Woking | - | H&F Shepherd’s Bush, Godalming Ockford Road 2|
|South West London| Richmond | London Teddington Bushy Park. |
|Hammersmith & Fulham|London Borough of Hammersmith and Fulham|-| H&F Hammersmith Town Centre, H&F Shepherd’s Bush|
|Watford|Hertfordshire and Bedfordshire|-|Watford Town Hall|
|Oxfordshire|Oxfordshire|-|Oxford High St, Oxford St Ebbes (Cal Club), Oxford Center Roadside, Oxford St Ebbes|
| Berkshire West| Readiing| - | Reading Caversham Road, Reading Oxford Road, Reading London Road, Reading New Town|

## Step 2: Format the Data

In [2]:
boroughs = ['hammersmithAndFulham', 'oxford', 'reading', 'watford']

In [3]:
li = []

for borough in boroughs:
    print(borough)
    df = pd.read_excel('./raw_data/{}.xlsx'.format(borough), header=[0,1], sheet_name=None)
    df = pd.concat(df.values(), axis=0)
    df = pd.DataFrame(df, columns=df.keys())
    li.append(df)

frame = pd.concat(li, axis=0, ignore_index=True)

hammersmithAndFulham
oxford
reading
watford

In [4]:
# frame.to_excel("concatinated_pollution_data.xlsx")

In [5]:
# df = pd.read_excel('concatinated_pollution_data.xlsx', header=[0,1], sheet_name=None)
# df = pd.concat(df.values(), axis=0)
# df = pd.DataFrame(df, columns=df.keys())
# df.head()

In [6]:
# pd.set_option('display.max_columns', 100)

## Step 3: Unify missing data

In [7]:
df = frame.replace('No data', np.nan)
df = df.replace('No Data', np.nan)
df.head()

Hourly measurement data supplied by UK-air on 05/01/2021 Hourly measurement data supplied by UK-air on 05/01/2021  \
All Data GMT hour ending                                                                 All Data GMT hour ending
0                                                                                                       NaN
1                                                                                                      Time
2                                                                                                  01:00:00
3                                                                                                  02:00:00
4                                                                                                  03:00:00

Hourly measurement data supplied by UK-air on 05/01/2021                             \
All Data GMT hour ending                                 All Data GMT hour ending.1
0                                                                          Broadway
1                                                                  Nitrogen dioxide
2                                                                               NaN
3                                                                               NaN
4                                                                               NaN

Hourly measurement data supplied by UK-air on 05/01/2021                              \
All Data GMT hour ending                                 All Data GMT hour ending.10
0                                                                                NaN
1                                                                             Status
2                                                                      V ugm-3 (VCM)
3                                                                      V ugm-3 (VCM)
4                                                                      V ugm-3 (VCM)

Hourly measurement data supplied by UK-air on 05/01/2021                               \
All Data GMT hour ending                                  All Data GMT hour ending.11
0                                                         H&F Hammersmith Town Centre
1                                                                               Ozone
2                                                                                 NaN
3                                                                                 NaN
4                                                                                 NaN

Hourly measurement data supplied by UK-air on 05/01/2021                              \
All Data GMT hour ending                                 All Data GMT hour ending.12
0                                                                                NaN
1                                                                             Status
2                                                                                NaN
3                                                                                NaN
4                                                                                NaN

Hourly measurement data supplied by UK-air on 05/01/2021                              \
All Data GMT hour ending                                 All Data GMT hour ending.13
0                                                                                NaN
1                                                                   Nitrogen dioxide
2                                                                                NaN
3                                                                                NaN
4                                                                                NaN

Hourly measurement data supplied by UK-air on 05/01/2021                              \
All Data GMT hour ending                                 All Data GMT hour ending.14
0                                                                                NaN
1                                                                             Status
2                                                                                NaN
3                                                                                NaN
4                                                                                NaN

Hourly measurement data supplied by UK-air on 05/01/2021                                             \
All Data GMT hour ending                                                All Data GMT hour ending.15
0                                                                                               NaN
1                                                         PM10 particulate matter (Hourly measured)
2                                                                                               NaN
3                                                                                               NaN
4                                                                                               NaN

Hourly measurement data supplied by UK-air on 05/01/2021                              \
All Data GMT hour ending                                 All Data GMT hour ending.16
0                                                                                NaN
1                                                                             Status
2                                                                                NaN
3                                                                                NaN
4                                                                                NaN

Hourly measurement data supplied by UK-air on 05/01/2021                                              \
All Data GMT hour ending                                                 All Data GMT hour ending.17
0                                                                                                NaN
1                                                         PM2.5 particulate matter (Hourly measured)
2                                                                                                NaN
3                                                                                                NaN
4                                                                                                NaN

Hourly measurement data supplied by UK-air on 05/01/2021                    ...                      \
All Data GMT hour ending                                                    ...
0                                                                           ...
1                                                                           ...
2                                                                           ...
3                                                                           ...
4                                                                           ...

Hourly measurement data supplied by UK-air on 05/01/2021                              \
All Data GMT hour ending                                 All Data GMT hour ending.24
0                                                                                NaN
1                                                                             Status
2                                                                                NaN
3                                                                                NaN
4                                                                                NaN

Hourly measurement data supplied by UK-air on 05/01/2021                                             \
All Data GMT hour ending                                                All Data GMT hour ending.25
0                                                                                               NaN
1                                                         PM10 particulate matter (Hourly measured)
2                                                                                               NaN
3                                                                                               NaN
4                                                                                               NaN

Hourly measurement data supplied by UK-air on 05/01/2021                              \
All Data GMT hour ending                                 All Data GMT hour ending.26
0                                                                                NaN
1                                                                             Status
2                                                                                NaN
3                                                                                NaN
4                                                                                NaN

Hourly measurement data supplied by UK-air on 05/01/2021                             \
All Data GMT hour ending                                 All Data GMT hour ending.3
0                                                                               NaN
1                                                                   Sulphur dioxide
2                                                                               NaN
3                                                                               NaN
4                                                                               NaN

Hourly measurement data supplied by UK-air on 05/01/2021                             \
All Data GMT hour ending                                 All Data GMT hour ending.4
0                                                                               NaN
1                                                                            Status
2                                                                           V ugm-3
3                                                                           V ugm-3
4                                                                           V ugm-3

Hourly measurement data supplied by UK-air on 05/01/2021                                             \
All Data GMT hour ending                                                 All Data GMT hour ending.5
0                                                                                               NaN
1                                                         PM10 particulate matter (Hourly measured)
2                                                                                               NaN
3                                                                                               NaN
4                                                                                               NaN

Hourly measurement data supplied by UK-air on 05/01/2021                             \
All Data GMT hour ending                                 All Data GMT hour ending.6
0                                                                               NaN
1                                                                            Status
2                                                                     V ugm-3 (VCM)
3                                                                     V ugm-3 (VCM)
4                                                                     V ugm-3 (VCM)

Hourly measurement data supplied by UK-air on 05/01/2021                             \
All Data GMT hour ending                                 All Data GMT hour ending.7
0                                                                       Brook Green
1                                                                  Nitrogen dioxide
2                                                                               NaN
3                                                                               NaN
4                                                                               NaN

Hourly measurement data supplied by UK-air on 05/01/2021                             \
All Data GMT hour ending                                 All Data GMT hour ending.8
0                                                                               NaN
1                                                                            Status
2                                                                           V ugm-3
3                                                                           V ugm-3
4                                                                           V ugm-3

Hourly measurement data supplied by UK-air on 05/01/2021
All Data GMT hour ending                                                 All Data GMT hour ending.9
0                                                                                               NaN
1                                                         PM10 particulate matter (Hourly measured)
2                                                                                               NaN
3                                                                                               NaN
4                                                                                               NaN

[5 rows x 27 columns]

## Step 4: Identify closed monitoring stations

In [8]:
non_null_columns = [col for col in df.columns if df.loc[:, col].notna().any()]
open_monitoring_sites = df[non_null_columns]
open_monitoring_sites

Hourly measurement data supplied by UK-air on 05/01/2021 Hourly measurement data supplied by UK-air on 05/01/2021  \
All Data GMT hour ending                                                                 All Data GMT hour ending
0                                                                                                       NaN
1                                                                                                      Time
2                                                                                                  01:00:00
3                                                                                                  02:00:00
4                                                                                                  03:00:00
5                                                                                                  04:00:00
6                                                                                                  05:00:00
7                                                                                                  06:00:00
8                                                                                                  07:00:00
9                                                                                                  08:00:00
10                                                                                                 09:00:00
11                                                                                                 10:00:00
12                                                                                                 11:00:00
13                                                                                                 12:00:00
14                                                                                                 13:00:00
15                                                                                                 14:00:00
16                                                                                                 15:00:00
17                                                                                                 16:00:00
18                                                                                                 17:00:00
19                                                                                                 18:00:00
20                                                                                                 19:00:00
21                                                                                                 20:00:00
22                                                                                                 21:00:00
23                                                                                                 22:00:00
24                                                                                                 23:00:00
25                                                                                      1900-01-01 00:00:00
26                                                                                                 01:00:00
27                                                                                                 02:00:00
28                                                                                                 03:00:00
29                                                                                                 04:00:00
...                                                                                                     ...
567922                                                                                             21:00:00
567923                                                                                             22:00:00
567924                                                                                             23:00:00
567925                                                                                  1900-01-01 00:00:00
567926                                                                                             01:00:00
567927                                                                                             02:00:00
567928                                                                                             03:00:00
567929                                                                                             04:00:00
567930                                                                                             05:00:00
567931                                                                                             06:00:00
567932                                                                                             07:00:00
567933                                                                                             08:00:00
567934                                                                                             09:00:00
567935                                                                                             10:00:00
567936                                                                                             11:00:00
567937                                                                                             12:00:00
567938                                                                                             13:00:00
567939                                                                                             14:00:00
567940                                                                                             15:00:00
567941                                                                                             16:00:00
567942                                                                                             17:00:00
567943                                                                                             18:00:00
567944                                                                                             19:00:00
567945                                                                                             20:00:00
567946                                                                                             21:00:00
567947                                                                                             22:00:00
567948                                                                                             23:00:00
567949                                                                                  1900-01-01 00:00:00
567950                                                                                                  NaN
567951                                                                                                  NaN

Hourly measurement data supplied by UK-air on 05/01/2021                             \
All Data GMT hour ending                                 All Data GMT hour ending.1
0                                                                          Broadway
1                                                                  Nitrogen dioxide
2                                                                               NaN
3                                                                               NaN
4                                                                               NaN
5                                                                               NaN
6                                                                               NaN
7                                                                               NaN
8                                                                               NaN
9                                                                               NaN
10                                                                              NaN
11                                                                              NaN
12                                                                              NaN
13                                                                              NaN
14                                                                              NaN
15                                                                              NaN
16                                                                              NaN
17                                                                              NaN
18                                                                              NaN
19                                                                              NaN
20                                                                              NaN
21                                                                              NaN
22                                                                              NaN
23                                                                              NaN
24                                                                              NaN
25                                                                              NaN
26                                                                              NaN
27                                                                              NaN
28                                                                              NaN
29                                                                              NaN
...                                                                             ...
567922                                                                          NaN
567923                                                                          NaN
567924                                                                          NaN
567925                                                                          NaN
567926                                                                          NaN
567927                                                                          NaN
567928                                                                          NaN
567929                                                                          NaN
567930                                                                          NaN
567931                                                                          NaN
567932                                                                          NaN
567933                                                                          NaN
567934                                                                          NaN
567935                                                                          NaN
567936                                                                          NaN
567937                                                                          NaN
567938                                                                          NaN
567939                                                                          NaN
567940                                                                          NaN
567941                                                                          NaN
567942                                                                          NaN
567943                                                                          NaN
567944                                                                          NaN
567945                                                                          NaN
567946                                                                          NaN
567947                                                                          NaN
567948                                                                          NaN
567949                                                                          NaN
567950                                                                          NaN
567951                                                                          NaN

Hourly measurement data supplied by UK-air on 05/01/2021                              \
All Data GMT hour ending                                 All Data GMT hour ending.10
0                                                                                NaN
1                                                                             Status
2                                                                      V ugm-3 (VCM)
3                                                                      V ugm-3 (VCM)
4                                                                      V ugm-3 (VCM)
5                                                                      V ugm-3 (VCM)
6                                                                      V ugm-3 (VCM)
7                                                                      V ugm-3 (VCM)
8                                                                      V ugm-3 (VCM)
9                                                                      V ugm-3 (VCM)
10                                                                     V ugm-3 (VCM)
11                                                                     V ugm-3 (VCM)
12                                                                     V ugm-3 (VCM)
13                                                                     V ugm-3 (VCM)
14                                                                     V ugm-3 (VCM)
15                                                                     V ugm-3 (VCM)
16                                                                     V ugm-3 (VCM)
17                                                                     V ugm-3 (VCM)
18                                                                     V ugm-3 (VCM)
19                                                                     V ugm-3 (VCM)
20                                                                     V ugm-3 (VCM)
21                                                                     V ugm-3 (VCM)
22                                                                     V ugm-3 (VCM)
23                                                                     V ugm-3 (VCM)
24                                                                     V ugm-3 (VCM)
25                                                                     V ugm-3 (VCM)
26                                                                     V ugm-3 (VCM)
27                                                                     V ugm-3 (VCM)
28                                                                     V ugm-3 (VCM)
29                                                                     V ugm-3 (VCM)
...                                                                              ...
567922                                                               N ugm-3 (FIDAS)
567923                                                               N ugm-3 (FIDAS)
567924                                                               N ugm-3 (FIDAS)
567925                                                               N ugm-3 (FIDAS)
567926                                                               N ugm-3 (FIDAS)
567927                                                               N ugm-3 (FIDAS)
567928                                                               N ugm-3 (FIDAS)
567929                                                               N ugm-3 (FIDAS)
567930                                                               N ugm-3 (FIDAS)
567931                                                               N ugm-3 (FIDAS)
567932                                                               N ugm-3 (FIDAS)
567933                                                               N ugm-3 (FIDAS)
567934                                                               N ugm-3 (FIDAS)
567935                                                               N ugm-3 (FIDAS)
567936                                                               N ugm-3 (FIDAS)
567937                                                               N ugm-3 (FIDAS)
567938                                                               N ugm-3 (FIDAS)
567939                                                               N ugm-3 (FIDAS)
567940                                                               N ugm-3 (FIDAS)
567941                                                               N ugm-3 (FIDAS)
567942                                                               N ugm-3 (FIDAS)
567943                                                               N ugm-3 (FIDAS)
567944                                                               N ugm-3 (FIDAS)
567945                                                               N ugm-3 (FIDAS)
567946                                                               N ugm-3 (FIDAS)
567947                                                               N ugm-3 (FIDAS)
567948                                                               N ugm-3 (FIDAS)
567949                                                               N ugm-3 (FIDAS)
567950                                                                           NaN
567951                                                                           NaN

Hourly measurement data supplied by UK-air on 05/01/2021                               \
All Data GMT hour ending                                  All Data GMT hour ending.11
0                                                         H&F Hammersmith Town Centre
1                                                                               Ozone
2                                                                                 NaN
3                                                                                 NaN
4                                                                                 NaN
5                                                                                 NaN
6                                                                                 NaN
7                                                                                 NaN
8                                                                                 NaN
9                                                                                 NaN
10                                                                                NaN
11                                                                                NaN
12                                                                                NaN
13                                                                                NaN
14                                                                                NaN
15                                                                                NaN
16                                                                                NaN
17                                                                                NaN
18                                                                                NaN
19                                                                                NaN
20                                                                                NaN
21                                                                                NaN
22                                                                                NaN
23                                                                                NaN
24                                                                                NaN
25                                                                                NaN
26                                                                                NaN

## Step 5: Setting Date and Time columns to Datetime

In [10]:
open_monitoring_sites[('Unnamed: 1_level_0','Time')] = [str(x)[-8:] for x in open_monitoring_sites[('Unnamed: 1_level_0','Time')]]

KeyError: ('Unnamed: 1_level_0', 'Time')

In [ ]:
open_monitoring_sites

In [ ]:
open_monitoring_sites[('Unnamed: 1_level_0','Time')] = pd.to_datetime(open_monitoring_sites[('Unnamed: 1_level_0','Time')], format='%H:%M:%S').dt.strftime("%H:%M:%S")

In [ ]:
open_monitoring_sites.columns

In [ ]:
open_monitoring_sites.set_index([('Unnamed: 0_level_0','Date'), ('Unnamed: 1_level_0','Time')], inplace=True)
open_monitoring_sites

In [ ]:
open_monitoring_sites = open_monitoring_sites.rename_axis(['Date','Time'])
open_monitoring_sites

## Step 6: Removing Multi-tier Columns

In [ ]:
open_monitoring_sites_stack = open_monitoring_sites.stack(0, dropna=True).rename_axis(('Date', 'Time','Location'))
open_monitoring_sites_stack

In [ ]:
open_monitoring_sites_stack.reset_index(level=['Location'])

## Renaming status columns

In [ ]:
list(open_monitoring_sites_stack.columns)

In [ ]:
pollutants = ['Carbon monoxide',
 'Nitric Oxide',
 'Nitrogen dioxide',
 'Non-volatile PM10',
 'Non-volatile PM2.5',
 'Oxides of Nitrogen',
 'Ozone',
 'PM1 Particulates',
 'PM10 Particulate matter',
 'PM10 particulate matter (Hourly measured)',
 'PM2.5 Particulate matter',
 'PM2.5 Particulate matter.1',
 'PM2.5 particulate matter (Hourly measured)',
 'Sulphur dioxide',
 'Volatile PM10']

In [ ]:
units = {'Status': 'Carbon monoxide units',
 'Status.1' : 'Nitric Oxide units',
 'Status.10' :'Nitrogen dioxide units',
 'Status.12' :'Non-volatile PM10 units',
 'Status.14' : 'Non-volatile PM2.5 units',
 'Status.2' : 'Oxides of Nitrogen units',
 'Status.3' : 'Ozone units',
 'Status.4' : 'PM1 Particulates units',
 'Status.5' : 'PM10 Particulate matter units',
 'Status.6' : 'PM10 particulate matter (Hourly measured) units',
 'Status.7' : 'PM2.5 Particulate matter units',
 'Status.8' : 'PM2.5 Particulate matter.1 units',
 'Status.9' : 'PM2.5 particulate matter (Hourly measured) units'
 }

In [ ]:
# open_monitoring_sites_stack.columns = open_monitoring_sites_stack.columns.map(units)

In [ ]:
open_monitoring_sites_stack.to_csv("stacked_inner_pollution_data.csv")

In [ ]:
# clean_data = pd.read_excel('concatinated_pollution_data.xlsx', header=[0,1], sheet_name=None)
# clean_dataclean_data = pd.concat(clean_data.values(), axis=0)
# clean_data = pd.DataFrame(clean_data, columns=clean_data.keys())
# clean_data.head()

## Next Steps

- Use API call to gather data from monitoring stations
- Investigate other data sources for mass downloads and ease
- Aggregate data on a daily basis
- Investigate similarities/differences between outer and inner locations, perform EDA on each
- Aggregate data annually and merge with Health and Flight data